# This is a basic workflow to help you get started with Actions

name: MacOs Desktop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Runs a set of commands using the runners shell
      - name: Installing Dependencies
        run: |
          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"        
          curl -LO https://github.com/macports/macports-base/releases/download/v2.8.1/MacPorts-2.8.1-12-Monterey.pkg
          sudo installer -pkg MacPorts-2.8.1-12-Monterey.pkg -target /
          sudo port install tigervnc
          curl -O https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-7.1.0-MacOSX-universal.pkg
          sudo installer -pkg VNC-Server-7.1.0-MacOSX-universal.pkg -target /
          ls /Applications/
          sudo /Applications/RealVNC/VNC\ Server.app/Contents/MacOS/vncserver_service
          pip install bs4 requests
          sudo lsof -i tcp -sTCP:LISTEN -P -n
      
      - name: Running a Remote Desktop
        env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
        run: |
          
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes -setvncpw -vncpw mypassword
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate
          sudo lsof -i tcp -sTCP:LISTEN -P -n
          python main.py 5900
