# This is a basic workflow to help you get started with Actions

name: MacOs Desktop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Runs a set of commands using the runners shell
      - name: Installing Dependencies
        run: |
          brew update
          brew install --cask xquartz
          brew install tightvnc
          pip install bs4 requests
      
      - name: Running a SSH Server
        env:
          PASSWORD: ${{secrets.PASSWORD}}
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
        run: |
          sudo cp /usr/local/opt/tightvnc/homebrew.mxcl.tightvncserver.plist ~/Library/LaunchAgents/
          sudo launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.tightvncserver.plist
          echo $PASSWORD | sudo -S vncserver -geometry 1337x768 -localhost no     
          python main.py 5901
