name: Windows Desktop

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Installing Dependencies
      run: |
        choco install tightvnc
        pip install bs4 requests

    - name: Running VNC Sever
      env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
      run: |
        set path=C:\Program Files\TightVNC
        reg add "HKCU\SOFTWARE\TightVNC\Server" /v "AllowLoopback" /t REG_DWORD /d 1 /f 
        echo ${{secrets.PASSWORD}} | vncpasswd -print -legacy | python -c "import os;a =input().split('=')[1];hex=' '.join(a[i:i+2] for i in range(0, len(a), 2));print(hex);os.system(f'echo y | reg add \"HKCU\SOFTWARE\TightVNC\Server\" /v \"Password\" /t REG_BINARY /d \"{hex}\"')"
        tvnserver
        python main.py 5900
        
