name: Windows Desktop

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Installing Dependencies
      run: |
        choco install tightvnc
        pip install bs4 requests

    - name: Running VNC Sever
      env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
      run: |
        REG IMPORT vnc-settings.reg
        echo ${{secrets.PASSWORD}} | .\vncpasswd -print -legacy | python -c "import os;hex=input().split('=')[1];os.system(f'echo y | REG ADD \`"HKCU\SOFTWARE\TightVNC\Server\`" /v \`"Password\`" /t REG_BINARY /d {hex}')"
        & "C:\Program Files\TightVNC\tvnserver.exe"
        python main.py 5900
        
