name: Windows Desktop

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Installing Dependencies
      run: |
        choco install vnc.install -y
        pip install bs4 requests

    - name: Running VNC Sever
      env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
      run: |
        vncserver.exe -kill :1 || echo "no vncserver running"
        echo ${{secrets.PASSWORD}} | vncpasswd.exe -f > ~/.vnc/passwd
        vncserver.exe :1 -geometry 1280x720 -depth 24
        python main.py 5900
        
