name: Windows Desktop

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Install VNC Server and Dependencies
      run: |
        choco install tightvnc -y
        pip install bs4 requests

    - name: Start VNC Server
      run: |
        & "C:\Program Files\TightVNC\tvnserver.exe" '-controlservice -start'

    - name: Set VNC Server Password
      run: |
        & "C:\Program Files\TightVNC\tvnserver.exe" -password "${{ secrets.PASSWORD }}"

    - name: Expose VNC Server Port
      run: |
        netsh advfirewall firewall add rule name="VNC Server" dir=in action=allow protocol=TCP localport=5901
        
    - name: Running VNC Sever
      env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
      run: |
        netstat -ano
        python main.py 5901
        
