name: Windows Desktop

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Installing Dependencies
      run: |
        choco install tightvnc -y
        pip install bs4 requests

    - name: Running VNC Sever
      env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
      run: |
        reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\Server" /v Enabled /t REG_DWORD /d 0xffffffff /f
        & "C:\Program Files\TightVNC\tvnserver.exe" -password "${{ secrets.PASSWORD }}"
        & "C:\Program Files\TightVNC\tvnserver.exe" '-controlservice -start'
        python main.py 5900
        
